// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ServiciosBarberoCliente.Models;

public partial class DirectBarber1Context : DbContext
{
    public DirectBarber1Context(DbContextOptions<DirectBarber1Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Rol> Rols { get; set; }

    public virtual DbSet<Solicitud> Solicituds { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Rol>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Rol__3214EC07262FF7AC");

            entity.ToTable("Rol");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Solicitud>(entity =>
        {
            entity.HasKey(e => e.IdSolicitud).HasName("PK__Solicitu__1E2B2178BF76A408");

            entity.ToTable("Solicitud");

            entity.Property(e => e.IdSolicitud).HasColumnName("id_Solicitud");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .HasColumnName("descripcion");
            entity.Property(e => e.Fecha)
                .HasColumnType("datetime")
                .HasColumnName("fecha");
            entity.Property(e => e.IdBarbero).HasColumnName("id_Barbero");
            entity.Property(e => e.IdCliente).HasColumnName("id_Cliente");
            entity.Property(e => e.Precio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio");

            entity.HasOne(d => d.IdBarberoNavigation).WithMany(p => p.SolicitudesComoBarbero)
                .HasForeignKey(d => d.IdBarbero)
                .HasConstraintName("FK__Solicitud__id_Ba__693CA210");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.SolicitudesComoCliente)
                .HasForeignKey(d => d.IdCliente)
                .HasConstraintName("FK__Solicitud__id_Cl__68487DD7");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuario__3214EC07ECF529DC");

            entity.ToTable("Usuario");

            entity.Property(e => e.Apellido)
                .HasMaxLength(50)
                .HasColumnName("apellido");
            entity.Property(e => e.Calificacion)
                .HasColumnType("decimal(3, 2)")
                .HasColumnName("calificacion");
            entity.Property(e => e.Contrasena)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("contrasena");
            entity.Property(e => e.Correo)
                .IsRequired()
                .HasMaxLength(60)
                .HasColumnName("correo");
            entity.Property(e => e.Direccion)
                .HasMaxLength(50)
                .HasColumnName("direccion");
            entity.Property(e => e.Documento)
                .HasMaxLength(10)
                .HasColumnName("documento");
            entity.Property(e => e.FecNacimiento).HasColumnName("fec_nacimiento");
            entity.Property(e => e.FecRegistro)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fec_registro");
            entity.Property(e => e.Foto).HasColumnName("foto");
            entity.Property(e => e.IdRol).HasColumnName("id_Rol");
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .HasColumnName("nombre");
            entity.Property(e => e.Telefono)
                .HasMaxLength(20)
                .HasColumnName("telefono");

            entity.HasOne(d => d.Rol).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Usuario__id_Rol__5165187F");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}