// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ServiciosBarberoCliente.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Correo { get; set; }

    public string Contrasena { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public DateTime? FecRegistro { get; set; }

    [DataType(DataType.Date)]
    [Display(Name = "Fecha de Nacimiento")]
    public DateOnly? FecNacimiento { get; set; }

    public decimal? Calificacion { get; set; }

    public string Foto { get; set; }

    [NotMapped]
    public IFormFile ImagenFile { get; set; }

    public string Documento { get; set; }


    public int IdRol { get; set; }
    public virtual Rol Rol { get; set; }

    public virtual ICollection<Solicitud> SolicitudesComoBarbero { get; set; } = new List<Solicitud>();

    public virtual ICollection<Solicitud> SolicitudesComoCliente { get; set; } = new List<Solicitud>();
}